#!/usr/bin/python3
import os
import sys

curr_dir = os.getcwd()

if os.getuid() != 0:
    print("Call this script with sudo: `sudo ./install`.")
    sys.exit(1)

# Ajouter le dépôt local à APT
with open("/etc/apt/sources.list.d/local.list", "w") as outfile:
    print(f"deb [trusted=yes] file://{curr_dir} ./", file=outfile)

# Générer l'index des paquets
os.system("dpkg-scanpackages . /dev/null > Packages")

# Mettre à jour APT
os.system("apt-get update")

# Installer les paquets
os.system("apt install mythicos-desktop mythicos-system")