#!/bin/sh
# postrm script for MythicOS

set -e

case "$1" in
    remove|purge)

        # désactiver le service
        if command -v update-rc.d >/dev/null 2>&1; then
            update-rc.d -f mythicos-system remove || true
        fi

        if command -v systemctl >/dev/null 2>&1; then
            systemctl disable mythicos-system.service || true
            systemctl daemon-reload || true
        fi

    ;;

    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
